version: "3.9"

services:
  instagram-story-challenge-base-node:
    image: instagram-story-challenge-base-node
    build:
      context: ..
      dockerfile: docker/Dockerfile

  api-gateway:
    image: instagram-story-challenge-base-node
    ports:
      - 3050:3050
    networks:
      - app-net
    environment:
      - APP_NAME=gateway
    command: './docker/init.sh'
    volumes:
      - './../apps/gateway:/project/apps/gateway:ro'
      - './../libs:/project/libs:ro'
      - './../environments/gateway.env:/project/environments/gateway.env:ro'
    depends_on:
      - redis

  user-service:
    image: instagram-story-challenge-base-node
    networks:
      - app-net
    environment:
      - APP_NAME=user-service
    command: './docker/init.sh'
    volumes:
      - './../apps/user-service:/project/apps/user-service:ro'
      - './../libs:/project/libs:ro'
      - './../environments/user-service.env:/project/environments/user-service.env:ro'
    depends_on:
      - mongo

  auth-service:
    image: instagram-story-challenge-base-node
    networks:
      - app-net
    environment:
      - APP_NAME=auth-service
    command: './docker/init.sh'
    volumes:
      - './../apps/auth-service:/project/apps/auth-service:ro'
      - './../libs:/project/libs:ro'
      - './../environments/auth-service.env:/project/environments/auth-service.env:ro'
    depends_on:
      - redis

  story-service:
    image: instagram-story-challenge-base-node
    networks:
      - app-net
    environment:
      - APP_NAME=story-service
    command: './docker/init.sh'
    volumes:
      - './../apps/story-service:/project/apps/story-service:ro'
      - './../libs:/project/libs:ro'
      - './../environments/story-service.env:/project/environments/story-service.env:ro'
    depends_on:
      - postgresql

  mongo:
    image: mongo
    ports:
      - 27016:27017
    networks:
      - app-net

  redis:
    image: redis
    ports:
      - 6378:6379
    networks:
      - app-net

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - app-net
    environment:
      POSTGRES_DB: "isc"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

networks:
  app-net: