version: "3.9"

services:
  instagram-story-challenge-base-node:
    image: instagram-story-challenge-base-node
    build:
      context: ..
      dockerfile: docker/Dockerfile

  api-gateway:
    image: instagram-story-challenge-base-node
    ports:
      - 3050:3050
    networks:
      - app-net
    environment:
      - APP_NAME=gateway
    command: './docker/init.sh'
    volumes:
      - './../apps/gateway:/project/apps/gateway:ro'
      - './../libs:/project/libs:ro'

  user-service:
    image: instagram-story-challenge-base-node
    networks:
      - app-net
    environment:
      - APP_NAME=user-service
    command: './docker/init.sh'
    volumes:
      - './../apps/user-service:/project/apps/user-service:ro'
      - './../libs:/project/libs:ro'
    depends_on:
      - mongo

  auth-service:
    image: instagram-story-challenge-base-node
    networks:
      - app-net
    environment:
      - APP_NAME=auth-service
    command: './docker/init.sh'
    volumes:
      - './../apps/auth-service:/project/apps/auth-service:ro'
      - './../libs:/project/libs:ro'
    depends_on:
      - redis

  mongo:
    image: mongo
    ports:
      - 27016:27017
    networks:
      - app-net

  redis:
    image: redis
    ports:
      - 6378:6379
    networks:
      - app-net

networks:
  app-net: